
overwrite: true

# Information about system.
system:

  # Total charge.
  charge: 0

  # Multiplicity.
  multiplicity: 1

rfile:

  path: data.zarr

  source_key: ./

  dest_key: opt_gfn2

  Z_label: atomic_numbers

  R_label: geometry

  R_opt_label: geometry

  E_opt_label: energy_ele_gfn2

  conv_opt_label: conv_opt

xtb:

  path: xtb

  # https://xtb-docs.readthedocs.io/en/latest/sp.html#accuracy
  acc: 0.01

  # https://xtb-docs.readthedocs.io/en/latest/optimization.html#optimization-levels
  opt_level: vtight

  # https://xtb-docs.readthedocs.io/en/latest/xcontrol.html#constraining-potentials
  constraints: null
  # Alternatively, below is an example where we add a constraint to xTB. These formats
  # create the nested lists format.
  # constraints:
  #   - 
  #     - distance
  #     - 
  #       - 0
  #       - 3
  #       - 1.4
  #   - 
  #     - angle
  #     - 
  #       - 4
  #       - 5
  #       - 6
  #       - auto

job:

  use_ray: true

  ray_address: auto

  n_workers: 2

  n_cpus_per_worker: 2

  chunk_size: 2

  start_slice: null

  end_slice: null
