# The Docker image that will be used to build your app
image: continuumio/miniconda3

# Functions that should be executed before the build script is run
before_script:
  - apt-get update && apt-get install build-essential -y
  - make refresh

pages:
  script:
    - make docs
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public/
  publish: public/
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
