#!/usr/bin/env python3

"""Run Psi4 optimizations"""

import sys
import argparse
import os
import yaml
import numpy as np
from reptar import File, Saver
from reptar.calculators.drivers import DriverOpt
from reptar.calculators.psi4_workers import psi4_opt
from reptar.utils import prep_group_opt
from reptar.logger import ReptarLogger, set_log_level

log = ReptarLogger(__name__)


def parse_args():
    parser = argparse.ArgumentParser(
        description="Prepare CREST jobs for configurational sampling"
    )
    parser.add_argument(
        "config_path",
        type=str,
        nargs="?",
        help="Path to YAML configuration file",
    )
    parser.add_argument(
        "--ray_address",
        type=str,
        nargs="?",
        default="",
        help="Desired ray address (will override config file)",
    )
    parser.add_argument(
        "--log_level",
        type=str,
        nargs="?",
        default="info",
        help="Desired logging level",
    )
    return parser.parse_args()


def main(args):
    log.info("Loading config.yaml")
    config_path = args.config_path
    with open(config_path, "r", encoding="utf-8") as stream:
        config = yaml.safe_load(stream)

    log.info("Opening data file")
    rfile_info = config["rfile"]
    rfile_path = os.path.abspath(rfile_info["path"])
    if os.path.exists(rfile_path):
        if config["overwrite"]:
            rfile = File(rfile_path, mode="a", allow_remove=True)
        else:
            log.error("%s exists and overwrite is False")
            sys.exit(0)
    else:
        rfile = File(rfile_path, mode="a", allow_remove=True)

    source_key = rfile_info["source_key"]
    dest_key = rfile_info["dest_key"]
    assert source_key != dest_key
    # pylint: disable-next=invalid-name
    Z_key = os.path.join(source_key, rfile_info["Z_label"])
    # pylint: disable-next=invalid-name
    R_key = os.path.join(source_key, rfile_info["R_label"])
    Z = rfile.get(Z_key)
    R = rfile.get(R_key)

    keys, data = prep_group_opt(
        rfile,
        Z_key,
        R_key,
        dest_key,
        Z_opt_label=rfile_info["Z_label"],
        conv_opt_label=rfile_info["conv_opt_label"],
        R_opt_label=rfile_info["R_opt_label"],
        E_opt_label=rfile_info["E_opt_label"],
    )
    saver = Saver(rfile_path, keys[1:])
    _, conv_opt, R_opt, E_opt = data  # pylint: disable=invalid-name

    log.info("Preparing worker options")
    worker_kwargs = {
        "charge": config["system"]["charge"],
        "mult": config["system"]["multiplicity"],
        "method": config["psi4"]["method"],
        "threads": config["job"]["n_cpus_per_worker"],
        "options": config["psi4"]["options"],
        "mem": config["job"]["mem_per_worker"],
    }

    start_slice = config["job"]["start_slice"]
    end_slice = config["job"]["end_slice"]
    ray_address = config["job"]["ray_address"]
    if args.ray_address != "":
        ray_address = args.ray_address
    driver = DriverOpt(
        psi4_opt,
        worker_kwargs,
        use_ray=config["job"]["use_ray"],
        n_workers=config["job"]["n_workers"],
        n_cpus_per_worker=config["job"]["n_cpus_per_worker"],
        chunk_size=config["job"]["chunk_size"],
        start_slice=start_slice,
        end_slice=end_slice,
        ray_address=ray_address,
    )
    log.info("Running optimizations")
    n_todo = int(np.count_nonzero(~conv_opt[start_slice:end_slice]))
    log.info("There are %r structures to optimize", n_todo)
    if n_todo > 0:
        driver.run(Z, R, conv_opt, R_opt, E_opt, saver=saver)
        log.info("Optimizations done")
    else:
        log.warning("Check your bounds if you are selecting a subset of structures")


if __name__ == "__main__":
    parsed_args = parse_args()
    set_log_level(parsed_args.log_level.upper())
    main(parsed_args)
