name: Codecov workflow

on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout reptar
        uses: actions/checkout@v2.5.0
      
      - name: Checkout reptar-data
        uses: actions/checkout@v2.5.0
        with:
          repository: 'aalexmmaldonado/reptar-data'
          lfs: true
          path: examples/reptar-data
      
      - name: Install dependencies
        run: |
          source "$CONDA/etc/profile.d/conda.sh"
          conda create -y --name reptar-test
          conda activate reptar-test
          conda install -y python=3.10 psi4 -c psi4
          pip install --upgrade pip
          pip install numpy exdir>=0.4.2 cclib>=1.7.0 scipy qcelemental>=0.25.1 pyyaml ase ray
          pip install pytest-cov pytest-order pytest-dependency
      
      - name: Run tests and collect coverage
        run: |
          source "$CONDA/etc/profile.d/conda.sh"
          conda activate reptar-test
          pytest --cov=reptar
      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          directory: /home/runner/work/reptar
          fail_ci_if_error: true
          verbose: true
