# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package TestPyPI

on:
  push:
    branches:
    - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    name: testpypi
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
          fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        # Set to the same as `PYTHON_VERSION` in `Makefile`
        python-version: "3.11"

    - name: Install poetry
      run: make conda-setup

    - name: Install dependencies
      run: make install

    - name: Build package
      run: make build

    - name: Publish package to TestPyPI
      uses: pypa/gh-action-pypi-publish@v1.8.10
      with:
        user: __token__
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository-url: https://test.pypi.org/legacy/
