# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
    - name: Checkout reptar
      uses: actions/checkout@v2.5.0
    
    - name: Checkout reptar-data
      uses: actions/checkout@v2.5.0
      with:
        repository: 'aalexmmaldonado/reptar-data'
        lfs: true
        path: examples/reptar-data
    
    - name: Setup conda conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: reptar-test
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        conda install -c psi4 psi4
        python -m pip install --upgrade pip
        python -m pip install numpy exdir>=0.4.2 cclib>=1.7.0 scipy qcelemental>=0.25.1 pyyaml ase ray
        python -m pip install pytest-cov pytest-order pytest-dependency
    
    - name: Install reptar
      run: pip install .
    - name: Test with pytest
      run: pytest .
